module.exports = [
    { name: 'Afghanistan', code: 'AF', isd: '+93' },
    { name: 'Albania', code: 'AL', isd: '+355' },
    { name: 'Algeria', code: 'DZ', isd: '+213' },
    { name: 'Andorra', code: 'AD', isd: '+376' },
    { name: 'Angola', code: 'AO', isd: '+244' },
    { name: 'Argentina', code: 'AR', isd: '+54' },
    { name: 'Armenia', code: 'AM', isd: '+374' },
    { name: 'Australia', code: 'AU', isd: '+61' },
    { name: 'Austria', code: 'AT', isd: '+43' },
    { name: 'Azerbaijan', code: 'AZ', isd: '+994' },
    { name: 'Bahrain', code: 'BH', isd: '+973' },
    { name: 'Bangladesh', code: 'BD', isd: '+880' },
    { name: 'Belarus', code: 'BY', isd: '+375' },
    { name: 'Belgium', code: 'BE', isd: '+32' },
    { name: 'Belize', code: 'BZ', isd: '+501' },
    { name: 'Benin', code: 'BJ', isd: '+229' },
    { name: 'Bhutan', code: 'BT', isd: '+975' },
    { name: 'Bolivia', code: 'BO', isd: '+591' },
    { name: 'Bosnia and Herzegovina', code: 'BA', isd: '+387' },
    { name: 'Botswana', code: 'BW', isd: '+267' },
    { name: 'Brazil', code: 'BR', isd: '+55' },
    { name: 'Brunei', code: 'BN', isd: '+673' },
    { name: 'Bulgaria', code: 'BG', isd: '+359' },
    { name: 'Burkina Faso', code: 'BF', isd: '+226' },
    { name: 'Burundi', code: 'BI', isd: '+257' },
    { name: 'Cambodia', code: 'KH', isd: '+855' },
    { name: 'Cameroon', code: 'CM', isd: '+237' },
    { name: 'Canada', code: 'CA', isd: '+1' },
    { name: 'Cape Verde', code: 'CV', isd: '+238' },
    { name: 'Central African Republic', code: 'CF', isd: '+236' },
    { name: 'Chad', code: 'TD', isd: '+235' },
    { name: 'Chile', code: 'CL', isd: '+56' },
    { name: 'China', code: 'CN', isd: '+86' },
    { name: 'Colombia', code: 'CO', isd: '+57' },
    { name: 'Comoros', code: 'KM', isd: '+269' },
    { name: 'Congo', code: 'CG', isd: '+242' },
    { name: 'Costa Rica', code: 'CR', isd: '+506' },
    { name: 'Croatia', code: 'HR', isd: '+385' },
    { name: 'Cuba', code: 'CU', isd: '+53' },
    { name: 'Cyprus', code: 'CY', isd: '+357' },
    { name: 'Czech Republic', code: 'CZ', isd: '+420' },
    { name: 'Denmark', code: 'DK', isd: '+45' },
    { name: 'Djibouti', code: 'DJ', isd: '+253' },
    { name: 'Ecuador', code: 'EC', isd: '+593' },
    { name: 'Egypt', code: 'EG', isd: '+20' },
    { name: 'El Salvador', code: 'SV', isd: '+503' },
    { name: 'Equatorial Guinea', code: 'GQ', isd: '+240' },
    { name: 'Eritrea', code: 'ER', isd: '+291' },
    { name: 'Estonia', code: 'EE', isd: '+372' },
    { name: 'Ethiopia', code: 'ET', isd: '+251' },
    { name: 'Fiji', code: 'FJ', isd: '+679' },
    { name: 'Finland', code: 'FI', isd: '+358' },
    { name: 'France', code: 'FR', isd: '+33' },
    { name: 'Gabon', code: 'GA', isd: '+241' },
    { name: 'Gambia', code: 'GM', isd: '+220' },
    { name: 'Georgia', code: 'GE', isd: '+995' },
    { name: 'Germany', code: 'DE', isd: '+49' },
    { name: 'Ghana', code: 'GH', isd: '+233' },
    { name: 'Greece', code: 'GR', isd: '+30' },
    { name: 'Guatemala', code: 'GT', isd: '+502' },
    { name: 'Guinea', code: 'GN', isd: '+224' },
    { name: 'Guinea-Bissau', code: 'GW', isd: '+245' },
    { name: 'Guyana', code: 'GY', isd: '+592' },
    { name: 'Haiti', code: 'HT', isd: '+509' },
    { name: 'Honduras', code: 'HN', isd: '+504' },
    { name: 'Hungary', code: 'HU', isd: '+36' },
    { name: 'Iceland', code: 'IS', isd: '+354' },
    { name: 'India', code: 'IN', isd: '+91' },
    { name: 'Indonesia', code: 'ID', isd: '+62' },
    { name: 'Iran', code: 'IR', isd: '+98' },
    { name: 'Iraq', code: 'IQ', isd: '+964' },
    { name: 'Ireland', code: 'IE', isd: '+353' },
    { name: 'Israel', code: 'IL', isd: '+972' },
    { name: 'Italy', code: 'IT', isd: '+39' },
    { name: 'Jamaica', code: 'JM', isd: '+1-876' },
    { name: 'Japan', code: 'JP', isd: '+81' },
    { name: 'Jordan', code: 'JO', isd: '+962' },
    { name: 'Kazakhstan', code: 'KZ', isd: '+7' },
    { name: 'Kenya', code: 'KE', isd: '+254' },
    { name: 'Kiribati', code: 'KI', isd: '+686' },
    { name: 'Kuwait', code: 'KW', isd: '+965' },
    { name: 'Kyrgyzstan', code: 'KG', isd: '+996' },
    { name: 'Laos', code: 'LA', isd: '+856' },
    { name: 'Latvia', code: 'LV', isd: '+371' },
    { name: 'Lebanon', code: 'LB', isd: '+961' },
    { name: 'Lesotho', code: 'LS', isd: '+266' },
    { name: 'Liberia', code: 'LR', isd: '+231' },
    { name: 'Libya', code: 'LY', isd: '+218' },
    { name: 'Liechtenstein', code: 'LI', isd: '+423' },
    { name: 'Lithuania', code: 'LT', isd: '+370' },
    { name: 'Luxembourg', code: 'LU', isd: '+352' },
    { name: 'Madagascar', code: 'MG', isd: '+261' },
    { name: 'Malawi', code: 'MW', isd: '+265' },
    { name: 'Malaysia', code: 'MY', isd: '+60' },
    { name: 'Maldives', code: 'MV', isd: '+960' },
    { name: 'Mali', code: 'ML', isd: '+223' },
    { name: 'Malta', code: 'MT', isd: '+356' },
    { name: 'Marshall Islands', code: 'MH', isd: '+692' },
    { name: 'Mauritania', code: 'MR', isd: '+222' },
    { name: 'Mauritius', code: 'MU', isd: '+230' },
    { name: 'Mexico', code: 'MX', isd: '+52' },
    { name: 'Micronesia', code: 'FM', isd: '+691' },
    { name: 'Moldova', code: 'MD', isd: '+373' },
    { name: 'Monaco', code: 'MC', isd: '+377' },
    { name: 'Mongolia', code: 'MN', isd: '+976' },
    { name: 'Montenegro', code: 'ME', isd: '+382' },
    { name: 'Morocco', code: 'MA', isd: '+212' },
    { name: 'Mozambique', code: 'MZ', isd: '+258' },
    { name: 'Myanmar', code: 'MM', isd: '+95' },
    { name: 'Namibia', code: 'NA', isd: '+264' },
    { name: 'Nauru', code: 'NR', isd: '+674' },
    { name: 'Nepal', code: 'NP', isd: '+977' },
    { name: 'Netherlands', code: 'NL', isd: '+31' },
    { name: 'New Zealand', code: 'NZ', isd: '+64' },
    { name: 'Nicaragua', code: 'NI', isd: '+505' },
    { name: 'Niger', code: 'NE', isd: '+227' },
    { name: 'Nigeria', code: 'NG', isd: '+234' },
    { name: 'North Korea', code: 'KP', isd: '+850' },
    { name: 'North Macedonia', code: 'MK', isd: '+389' },
    { name: 'Norway', code: 'NO', isd: '+47' },
    { name: 'Oman', code: 'OM', isd: '+968' },
    { name: 'Pakistan', code: 'PK', isd: '+92' },
    { name: 'Palau', code: 'PW', isd: '+680' },
    { name: 'Panama', code: 'PA', isd: '+507' },
    { name: 'Papua New Guinea', code: 'PG', isd: '+675' },
    { name: 'Paraguay', code: 'PY', isd: '+595' },
    { name: 'Peru', code: 'PE', isd: '+51' },
    { name: 'Philippines', code: 'PH', isd: '+63' },
    { name: 'Poland', code: 'PL', isd: '+48' },
    { name: 'Portugal', code: 'PT', isd: '+351' },
    { name: 'Qatar', code: 'QA', isd: '+974' },
    { name: 'Romania', code: 'RO', isd: '+40' },
    { name: 'Russia', code: 'RU', isd: '+7' },
    { name: 'Rwanda', code: 'RW', isd: '+250' },
    { name: 'Saint Kitts and Nevis', code: 'KN', isd: '+1-869' },
    { name: 'Saint Lucia', code: 'LC', isd: '+1-758' },
    { name: 'Samoa', code: 'WS', isd: '+685' },
    { name: 'San Marino', code: 'SM', isd: '+378' },
    { name: 'Sao Tome and Principe', code: 'ST', isd: '+239' },
    { name: 'Saudi Arabia', code: 'SA', isd: '+966' },
    { name: 'Senegal', code: 'SN', isd: '+221' },
    { name: 'Serbia', code: 'RS', isd: '+381' },
    { name: 'Seychelles', code: 'SC', isd: '+248' },
    { name: 'Sierra Leone', code: 'SL', isd: '+232' },
    { name: 'Singapore', code: 'SG', isd: '+65' },
    { name: 'Slovakia', code: 'SK', isd: '+421' },
    { name: 'Slovenia', code: 'SI', isd: '+386' },
    { name: 'Solomon Islands', code: 'SB', isd: '+677' },
    { name: 'Somalia', code: 'SO', isd: '+252' },
    { name: 'South Africa', code: 'ZA', isd: '+27' },
    { name: 'South Korea', code: 'KR', isd: '+82' },
    { name: 'South Sudan', code: 'SS', isd: '+211' },
    { name: 'Spain', code: 'ES', isd: '+34' },
    { name: 'Sri Lanka', code: 'LK', isd: '+94' },
    { name: 'Sudan', code: 'SD', isd: '+249' },
    { name: 'Suriname', code: 'SR', isd: '+597' },
    { name: 'Sweden', code: 'SE', isd: '+46' },
    { name: 'Switzerland', code: 'CH', isd: '+41' },
    { name: 'Syria', code: 'SY', isd: '+963' },
    { name: 'Taiwan', code: 'TW', isd: '+886' },
    { name: 'Tajikistan', code: 'TJ', isd: '+992' },
    { name: 'Tanzania', code: 'TZ', isd: '+255' },
    { name: 'Thailand', code: 'TH', isd: '+66' },
    { name: 'Timor-Leste', code: 'TL', isd: '+670' },
    { name: 'Togo', code: 'TG', isd: '+228' },
    { name: 'Tonga', code: 'TO', isd: '+676' },
    { name: 'Trinidad and Tobago', code: 'TT', isd: '+1-868' },
    { name: 'Tunisia', code: 'TN', isd: '+216' },
    { name: 'Turkey', code: 'TR', isd: '+90' },
    { name: 'Turkmenistan', code: 'TM', isd: '+993' },
    { name: 'Tuvalu', code: 'TV', isd: '+688' },
    { name: 'Uganda', code: 'UG', isd: '+256' },
    { name: 'Ukraine', code: 'UA', isd: '+380' },
    { name: 'United Arab Emirates', code: 'AE', isd: '+971' },
    { name: 'United Kingdom', code: 'GB', isd: '+44' },
    { name: 'United States', code: 'US', isd: '+1' },
    { name: 'Uruguay', code: 'UY', isd: '+598' },
    { name: 'Uzbekistan', code: 'UZ', isd: '+998' },
    { name: 'Vanuatu', code: 'VU', isd: '+678' },
    { name: 'Vatican City', code: 'VA', isd: '+379' },
    { name: 'Venezuela', code: 'VE', isd: '+58' },
    { name: 'Vietnam', code: 'VN', isd: '+84' },
    { name: 'Yemen', code: 'YE', isd: '+967' },
    { name: 'Zambia', code: 'ZM', isd: '+260' },
    { name: 'Zimbabwe', code: 'ZW', isd: '+263' }
];
